/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AfiliacionRouteImport } from './routes/afiliacion'
import { Route as ApoyoRouteImport } from './routes/apoyo'
import { Route as BeneficiosRouteImport } from './routes/beneficios'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as DerechosRouteImport } from './routes/derechos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as SindicatoRouteImport } from './routes/sindicato'
import { Route as DerechosIndexRouteImport } from './routes/derechos.index'
import { Route as DerechosCondicionesGeneralesRouteImport } from './routes/derechos.condiciones-generales'
import { Route as DerechosPersonalDeConfianzaRouteImport } from './routes/derechos.personal-de-confianza'
import { Route as DerechosPreguntasFrecuentesRouteImport } from './routes/derechos.preguntas-frecuentes'
import { Route as DerechosPrestacionesRouteImport } from './routes/derechos.prestaciones'
import { Route as DerechosSeguridadSocialRouteImport } from './routes/derechos.seguridad-social'
import { Route as NoticiasIndexRouteImport } from './routes/noticias.index'
import { Route as NoticiasSlugRouteImport } from './routes/noticias.$slug'
import { Route as SindicatoTransparenciaRouteImport } from './routes/sindicato.transparencia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AfiliacionRoute = AfiliacionRouteImport.update({
  id: '/afiliacion',
  path: '/afiliacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyoRoute = ApoyoRouteImport.update({
  id: '/apoyo',
  path: '/apoyo',
  getParentRoute: () => rootRouteImport,
} as any)
const BeneficiosRoute = BeneficiosRouteImport.update({
  id: '/beneficios',
  path: '/beneficios',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const DerechosRoute = DerechosRouteImport.update({
  id: '/derechos',
  path: '/derechos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const SindicatoRoute = SindicatoRouteImport.update({
  id: '/sindicato',
  path: '/sindicato',
  getParentRoute: () => rootRouteImport,
} as any)
const DerechosIndexRoute = DerechosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DerechosRoute,
} as any)
const DerechosCondicionesGeneralesRoute =
  DerechosCondicionesGeneralesRouteImport.update({
    id: '/condiciones-generales',
    path: '/condiciones-generales',
    getParentRoute: () => DerechosRoute,
  } as any)
const DerechosPersonalDeConfianzaRoute =
  DerechosPersonalDeConfianzaRouteImport.update({
    id: '/personal-de-confianza',
    path: '/personal-de-confianza',
    getParentRoute: () => DerechosRoute,
  } as any)
const DerechosPreguntasFrecuentesRoute =
  DerechosPreguntasFrecuentesRouteImport.update({
    id: '/preguntas-frecuentes',
    path: '/preguntas-frecuentes',
    getParentRoute: () => DerechosRoute,
  } as any)
const DerechosPrestacionesRoute = DerechosPrestacionesRouteImport.update({
  id: '/prestaciones',
  path: '/prestaciones',
  getParentRoute: () => DerechosRoute,
} as any)
const DerechosSeguridadSocialRoute = DerechosSeguridadSocialRouteImport.update({
  id: '/seguridad-social',
  path: '/seguridad-social',
  getParentRoute: () => DerechosRoute,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NoticiasRoute,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => NoticiasRoute,
} as any)
const SindicatoTransparenciaRoute = SindicatoTransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => SindicatoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/afiliacion': typeof AfiliacionRoute
  '/apoyo': typeof ApoyoRoute
  '/beneficios': typeof BeneficiosRoute
  '/contacto': typeof ContactoRoute
  '/derechos': typeof DerechosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/sindicato': typeof SindicatoRouteWithChildren
  '/derechos/condiciones-generales': typeof DerechosCondicionesGeneralesRoute
  '/derechos/personal-de-confianza': typeof DerechosPersonalDeConfianzaRoute
  '/derechos/preguntas-frecuentes': typeof DerechosPreguntasFrecuentesRoute
  '/derechos/prestaciones': typeof DerechosPrestacionesRoute
  '/derechos/seguridad-social': typeof DerechosSeguridadSocialRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/sindicato/transparencia': typeof SindicatoTransparenciaRoute
  '/derechos/': typeof DerechosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/afiliacion': typeof AfiliacionRoute
  '/apoyo': typeof ApoyoRoute
  '/beneficios': typeof BeneficiosRoute
  '/contacto': typeof ContactoRoute
  '/sindicato': typeof SindicatoRouteWithChildren
  '/derechos/condiciones-generales': typeof DerechosCondicionesGeneralesRoute
  '/derechos/personal-de-confianza': typeof DerechosPersonalDeConfianzaRoute
  '/derechos/preguntas-frecuentes': typeof DerechosPreguntasFrecuentesRoute
  '/derechos/prestaciones': typeof DerechosPrestacionesRoute
  '/derechos/seguridad-social': typeof DerechosSeguridadSocialRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/sindicato/transparencia': typeof SindicatoTransparenciaRoute
  '/derechos': typeof DerechosIndexRoute
  '/noticias': typeof NoticiasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/afiliacion': typeof AfiliacionRoute
  '/apoyo': typeof ApoyoRoute
  '/beneficios': typeof BeneficiosRoute
  '/contacto': typeof ContactoRoute
  '/derechos': typeof DerechosRouteWithChildren
  '/noticias': typeof NoticiasRouteWithChildren
  '/sindicato': typeof SindicatoRouteWithChildren
  '/derechos/condiciones-generales': typeof DerechosCondicionesGeneralesRoute
  '/derechos/personal-de-confianza': typeof DerechosPersonalDeConfianzaRoute
  '/derechos/preguntas-frecuentes': typeof DerechosPreguntasFrecuentesRoute
  '/derechos/prestaciones': typeof DerechosPrestacionesRoute
  '/derechos/seguridad-social': typeof DerechosSeguridadSocialRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/sindicato/transparencia': typeof SindicatoTransparenciaRoute
  '/derechos/': typeof DerechosIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/afiliacion'
    | '/apoyo'
    | '/beneficios'
    | '/contacto'
    | '/derechos'
    | '/noticias'
    | '/sindicato'
    | '/derechos/condiciones-generales'
    | '/derechos/personal-de-confianza'
    | '/derechos/preguntas-frecuentes'
    | '/derechos/prestaciones'
    | '/derechos/seguridad-social'
    | '/noticias/$slug'
    | '/sindicato/transparencia'
    | '/derechos/'
    | '/noticias/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/afiliacion'
    | '/apoyo'
    | '/beneficios'
    | '/contacto'
    | '/sindicato'
    | '/derechos/condiciones-generales'
    | '/derechos/personal-de-confianza'
    | '/derechos/preguntas-frecuentes'
    | '/derechos/prestaciones'
    | '/derechos/seguridad-social'
    | '/noticias/$slug'
    | '/sindicato/transparencia'
    | '/derechos'
    | '/noticias'
  id:
    | '__root__'
    | '/'
    | '/afiliacion'
    | '/apoyo'
    | '/beneficios'
    | '/contacto'
    | '/derechos'
    | '/noticias'
    | '/sindicato'
    | '/derechos/condiciones-generales'
    | '/derechos/personal-de-confianza'
    | '/derechos/preguntas-frecuentes'
    | '/derechos/prestaciones'
    | '/derechos/seguridad-social'
    | '/noticias/$slug'
    | '/sindicato/transparencia'
    | '/derechos/'
    | '/noticias/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AfiliacionRoute: typeof AfiliacionRoute
  ApoyoRoute: typeof ApoyoRoute
  BeneficiosRoute: typeof BeneficiosRoute
  ContactoRoute: typeof ContactoRoute
  DerechosRoute: typeof DerechosRouteWithChildren
  NoticiasRoute: typeof NoticiasRouteWithChildren
  SindicatoRoute: typeof SindicatoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/afiliacion': {
      id: '/afiliacion'
      path: '/afiliacion'
      fullPath: '/afiliacion'
      preLoaderRoute: typeof AfiliacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoyo': {
      id: '/apoyo'
      path: '/apoyo'
      fullPath: '/apoyo'
      preLoaderRoute: typeof ApoyoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beneficios': {
      id: '/beneficios'
      path: '/beneficios'
      fullPath: '/beneficios'
      preLoaderRoute: typeof BeneficiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derechos': {
      id: '/derechos'
      path: '/derechos'
      fullPath: '/derechos'
      preLoaderRoute: typeof DerechosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sindicato': {
      id: '/sindicato'
      path: '/sindicato'
      fullPath: '/sindicato'
      preLoaderRoute: typeof SindicatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/derechos/': {
      id: '/derechos/'
      path: '/'
      fullPath: '/derechos/'
      preLoaderRoute: typeof DerechosIndexRouteImport
      parentRoute: typeof DerechosRoute
    }
    '/derechos/condiciones-generales': {
      id: '/derechos/condiciones-generales'
      path: '/condiciones-generales'
      fullPath: '/derechos/condiciones-generales'
      preLoaderRoute: typeof DerechosCondicionesGeneralesRouteImport
      parentRoute: typeof DerechosRoute
    }
    '/derechos/personal-de-confianza': {
      id: '/derechos/personal-de-confianza'
      path: '/personal-de-confianza'
      fullPath: '/derechos/personal-de-confianza'
      preLoaderRoute: typeof DerechosPersonalDeConfianzaRouteImport
      parentRoute: typeof DerechosRoute
    }
    '/derechos/preguntas-frecuentes': {
      id: '/derechos/preguntas-frecuentes'
      path: '/preguntas-frecuentes'
      fullPath: '/derechos/preguntas-frecuentes'
      preLoaderRoute: typeof DerechosPreguntasFrecuentesRouteImport
      parentRoute: typeof DerechosRoute
    }
    '/derechos/prestaciones': {
      id: '/derechos/prestaciones'
      path: '/prestaciones'
      fullPath: '/derechos/prestaciones'
      preLoaderRoute: typeof DerechosPrestacionesRouteImport
      parentRoute: typeof DerechosRoute
    }
    '/derechos/seguridad-social': {
      id: '/derechos/seguridad-social'
      path: '/seguridad-social'
      fullPath: '/derechos/seguridad-social'
      preLoaderRoute: typeof DerechosSeguridadSocialRouteImport
      parentRoute: typeof DerechosRoute
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof NoticiasRoute
    }
    '/sindicato/transparencia': {
      id: '/sindicato/transparencia'
      path: '/transparencia'
      fullPath: '/sindicato/transparencia'
      preLoaderRoute: typeof SindicatoTransparenciaRouteImport
      parentRoute: typeof SindicatoRoute
    }
  }
}

interface DerechosRouteChildren {
  DerechosCondicionesGeneralesRoute: typeof DerechosCondicionesGeneralesRoute
  DerechosPersonalDeConfianzaRoute: typeof DerechosPersonalDeConfianzaRoute
  DerechosPreguntasFrecuentesRoute: typeof DerechosPreguntasFrecuentesRoute
  DerechosPrestacionesRoute: typeof DerechosPrestacionesRoute
  DerechosSeguridadSocialRoute: typeof DerechosSeguridadSocialRoute
  DerechosIndexRoute: typeof DerechosIndexRoute
}

const DerechosRouteChildren: DerechosRouteChildren = {
  DerechosCondicionesGeneralesRoute: DerechosCondicionesGeneralesRoute,
  DerechosPersonalDeConfianzaRoute: DerechosPersonalDeConfianzaRoute,
  DerechosPreguntasFrecuentesRoute: DerechosPreguntasFrecuentesRoute,
  DerechosPrestacionesRoute: DerechosPrestacionesRoute,
  DerechosSeguridadSocialRoute: DerechosSeguridadSocialRoute,
  DerechosIndexRoute: DerechosIndexRoute,
}

const DerechosRouteWithChildren = DerechosRoute._addFileChildren(
  DerechosRouteChildren,
)

interface NoticiasRouteChildren {
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
}

const NoticiasRouteChildren: NoticiasRouteChildren = {
  NoticiasSlugRoute: NoticiasSlugRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
}

const NoticiasRouteWithChildren = NoticiasRoute._addFileChildren(
  NoticiasRouteChildren,
)

interface SindicatoRouteChildren {
  SindicatoTransparenciaRoute: typeof SindicatoTransparenciaRoute
}

const SindicatoRouteChildren: SindicatoRouteChildren = {
  SindicatoTransparenciaRoute: SindicatoTransparenciaRoute,
}

const SindicatoRouteWithChildren = SindicatoRoute._addFileChildren(
  SindicatoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AfiliacionRoute: AfiliacionRoute,
  ApoyoRoute: ApoyoRoute,
  BeneficiosRoute: BeneficiosRoute,
  ContactoRoute: ContactoRoute,
  DerechosRoute: DerechosRouteWithChildren,
  NoticiasRoute: NoticiasRouteWithChildren,
  SindicatoRoute: SindicatoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
